### ISSUE TITLE
screen resolution  

### ISSUE THREAD

**Issue by chikachika1** [ManlyMarco/KK-HF_Patch#80] opened 2024-03-21 16:51 UTC
hf patch launcher isn't detecting my screen resolution, and the correct option is missing. i have to manually set it up every time I launch the game through the graphics settings plugin.

**Comment by ManlyMarco** [comment] 2024-03-21 19:23
What is the resolution? What version of the patch? How many displays? What are you setting?

**Comment by ManlyMarco** [comment] 2024-03-22 07:39
Duplicate of https://github.com/IllusionMods/IllusionLaunchers/issues/20

**Closed by ManlyMarco** 2024-03-22 07:39 UTC
